# This file lints the code, builds a package and then deploys it.
# For the deployment, $BINTRAY_USER, $BINTRAY_KEY and $GH_TOKEN environment
# variables need to be set.
language: php

matrix:
    include:
        - php: 7.2
        - php: 7.1
        - php: 7.0
          env: CS_FIXER=true LINT_JS=true
        - php: 5.6
        - php: 5.5
        - php: 5.4
          env: DEPLOY=true
    fast_finish: true

addons:
    apt:
        packages:
            - jq

cache:
    directories:
        - vendor
        - $HOME/.composer/cache

before_install:
    - nvm install 6
    - npm install -g grunt-cli
    - npm install
    - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi
    - utils/install-phars.sh

install:
    - composer self-update

before_script:
    - phpenv config-rm xdebug.ini
    - composer install --prefer-dist --no-interaction

script:
    - if [ "$LINT_JS" = true ]; then grunt lint:client; fi
    - grunt lint:server
    - if [ "$CS_FIXER" = true ]; then grunt cs:server; fi

before_deploy:
    - source utils/package.sh
    - source utils/bintray.sh

deploy:
    - provider: bintray
      file: utils/bintray.json
      user: $BINTRAY_USER
      key: $BINTRAY_KEY
      skip_cleanup: true
      on:
          condition: $DEPLOY = true
    - provider: releases
      api_key: $GH_TOKEN
      file: $SELFOSS_ZIPBALL
      skip_cleanup: true
      on:
          tags: true
          condition: $DEPLOY = true
